language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode6.4
    - os: osx
      osx_image: xcode8.2
    - os: osx
      osx_image: xcode10.3
    - os: osx
      osx_image: xcode11
    - os: osx
      osx_image: xcode11.1
    - os: osx
      osx_image: xcode11.2
    - os: osx
      osx_image: xcode11.3
      
script:
  - find / -xdev -perm +111 -name "*lldb*" -type f 2>&1 | egrep -v "Permission denied|Operation not permitted" || true
  - ls -la /Applications/Xcode.app/Contents/Developer/usr/bin/lldb-mi
