language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: windows
      before_install:
      - choco install python  
    - os: osx
      osx_image: xcode6.4
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode10.3
    - os: osx
      osx_image: xcode11.3
      
script:
  - cmake --version
  - python --version
  - python3 --version || true
  - pip install --user requests || true
  - pip3 install --user requests || true
  - find /usr/bin /Library/Developer /Applications/Xcode* -perm +111 -path "*bin/lldb*" -type f -exec ls -laF {} \;  -exec {} --version \; -exec sh -c "{} --help | egrep MI" \; || true
#  - ls -la /Applications/Xcode.app/Contents/Developer/usr/bin/lldb-mi
