language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode6.4
    - os: osx
      osx_image: xcode8.2
    - os: osx
      osx_image: xcode10.3
    - os: osx
      osx_image: xcode11
    - os: osx
      osx_image: xcode11.1
    - os: osx
      osx_image: xcode11.2
    - os: osx
      osx_image: xcode11.3
      
script:
  - find /usr/bin /Library/Developer /Applications/Xcode* -perm +111 -path "*bin/lldb*" -type f || true
  - ls -la /Applications/Xcode.app/Contents/Developer/usr/bin/lldb-mi
