language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode6.4
    - os: osx
      osx_image: xcode8.2
    - os: osx
      osx_image: xcode11.3
      
script:
  - ls -la /Applications/Xcode.app/Contents/Developer/usr/bin/lldb-mi
