language: cpp

cache:
  pip: true
  directories:
    - $HOME/.pyenv_cache
    - $HOME/.pyenv
    
matrix:
  include:
    - os: linux
      name: "Xenial 16.04"
      dist: xenial
      env: PYENV_VERSION=3.7
    - os: linux
      name: "Bionic 18.04"
      dist: bionic
      env: PYENV_VERSION=3.7
    - os: osx
      name: "Xcode 8.3"
      osx_image: xcode8.3
      addons:
        homebrew:
          packages: python3      
    - os: osx
      name: "Xcode 9.4"
      osx_image: xcode9.4
      addons:
        homebrew:
          packages: python3      
    - os: osx
      name: "Xcode 11.3"
      osx_image: xcode11.3
      
script:
  - echo $TRAVIS_OS_NAME
  - pyenv versions
  - python3 --version
  - pip3 install --user requests
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      find /Users /System /usr -xdev -perm -111 -type f -name "python*" -not -name "*-config" 2>&1 | \
        egrep -v "not permitted|Permission denied"
    fi
