language: cpp

cache:
  pip: true
  directories:
    - $HOME/.pyenv_cache
    - $HOME/.pyenv

env: PYENV_VERSION=3.7 PATH=$PATH:~/Library/Python/3.7/bin

matrix:
  include:
    - os: linux
      name: "Xenial 16.04"
      dist: xenial
    - os: linux
      name: "Bionic 18.04"
      dist: bionic
    - os: osx
      name: "Xcode 9.4"
      osx_image: xcode9.4
      addons:
        homebrew:
          packages: python3      
    - os: osx
      name: "Xcode 11.3"
      osx_image: xcode11.3
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      addons:
        homebrew:
          update: true
          packages: python3

script:
  - python3 --version
  - pip3 install --user conan
  - conan --version

